[package]
org = "ballerina"
name = "protobuf"
version = "@toml.version@"
distribution = "slbeta3"
export = ["protobuf", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]
