[package]
org = "ballerina"
name = "protobuf"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/module-ballerina-protobuf"
license = ["Apache-2.0"]
distribution = "2201.0.0"
export = ["protobuf", "protobuf.types.any", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]

[[platform.java11.dependency]]
path = "../native/build/libs/protobuf-native-@project.version@.jar"
