[package]
org = "ballerina"
name = "protobuf"
version = "@toml.version@"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/module-ballerina-protobuf"
license = ["Apache-2.0"]
distribution = "slbeta3"
export = ["protobuf", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]
