[package]
org = "ballerina"
name = "protobuf"
version = "1.1.0"
authors = ["Ballerina"]
keywords = ["wrappers"]
repository = "https://github.com/ballerina-platform/module-ballerina-protobuf"
license = ["Apache-2.0"]
distribution = "slbeta6"
export = ["protobuf", "protobuf.types.any", "protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]

[[platform.java11.dependency]]
path = "../native/build/libs/protobuf-native-1.1.0-SNAPSHOT.jar"
