[package]
org = "ballerina"
name = "protobuf"
version = "1.0.0"
distribution = "slbeta3"
export = ["protobuf.types.duration", "protobuf.types.empty", "protobuf.types.struct", "protobuf.types.timestamp", "protobuf.types.wrappers"]
